# RuboCop configuration for Sinatra project
# Configuración básica y limpia para aplicaciones Sinatra

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'

# ==========================================
# LAYOUT - Formato y presentación del código
# ==========================================

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config.ru'
    - 'db/migrations/**/*'

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# ==========================================
# METRICS - Límites de complejidad y tamaño
# ==========================================

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'
    - 'db/migrations/**/*'
    - 'app/routes/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'
    - 'app.rb'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'
    - 'config.ru'
    - 'app/routes/**/*'
    - 'db/migrations/**/*'
    - 'Rakefile'

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'
    - 'db/migrations/**/*'
    - 'app/routes/**/*'
    - 'app/helpers/error_handlers.rb' 

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'app/routes/**/*'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'app/routes/**/*'

# ==========================================
# STYLE - Estilo del código
# ==========================================

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatString:
  EnforcedStyle: format

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantBegin:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

# ==========================================
# LINT - Prevención de errores
# ==========================================

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedBlockArgument:
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: true

Lint/SuppressedException:
  AllowComments: true

Lint/IneffectiveAccessModifier:
  Enabled: true

# ==========================================
# NAMING - Convenciones de nombres
# ==========================================

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/MethodName:
  EnforcedStyle: snake_case

# ==========================================
# BUNDLER - Gemfile
# ==========================================

Bundler/OrderedGems:
  Enabled: true

# ==========================================
# SECURITY - Seguridad
# ==========================================

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true