AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'spec/spec_helper.rb'

require:
  - rubocop-rspec

# Increase line length limit
Layout/LineLength:
  Max: 120

# Allow longer methods in tests
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'

# Allow longer classes
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'

# Allow longer blocks in tests and seeds
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'
    - 'config.ru'

# Allow longer modules
Metrics/ModuleLength:
  Max: 150

# Disable ABC size for seeds and specs
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'lib/seeds.rb'

# Documentation comments
Style/Documentation:
  Enabled: false

# Allow top-level class/module definitions
Style/ClassAndModuleChildren:
  Enabled: false

# Prefer double quotes
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Allow trailing commas
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Allow empty rescue
Lint/SuppressedException:
  Enabled: false

# RSpec specific
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4